name: Test Action

on:
  push:
    branches: [main]
  workflow_dispatch:  # allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 24f2005647@ds.study.iitm.ac.in
        run: echo "Hello, world!"
